apiVersion: v1
kind: Service
metadata:
  namespace: eshop
  name: aws-ses-rest-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: aws-ses-rest-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eshop
  name: aws-ses-rest-api
  labels:
    app: aws-ses-rest-api
spec:
  selector:
    matchLabels:
      app: aws-ses-rest-api
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-ses-rest-api
    spec:
      containers:
        - name: aws-ses-rest-api
          image: maxmorev/aws-ses-rest-api:latest
          ports:
            - containerPort: 8080
              name: springboot
          resources:
            requests:
              memory: "200Mi"
              cpu: "250m" # 1/4 core
            limits:
              memory: "250Mi"
              cpu: "250m" # 1 core
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 80
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_REGION

