apiVersion: v1
kind: Namespace
metadata:
  name: eshop
  labels:
    app.kubernetes.io/name: eshop
    app.kubernetes.io/instance: eshop
---
apiVersion: v1
kind: Secret
metadata:
  namespace: eshop
  name: aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: {AWS_SECRET_ACCESS_KEY}
  AWS_REGION: {AWS_REGION}
