spring:
  application:
    name: aws-ses-rest-api
  profiles:
    active: dev

server:
  port: 8080

ses:
  source: "info@titsonfire.store"
  set: "configset-ses"

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: false
